# Generated by Django 6.0.2 on 2026-02-04 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsifi', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rasmi', models.ImageField(upload_to='products/')),
                ('omborda_bor', models.PositiveIntegerField(default=0)),
                ('qoshgan_sana', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='products.category')),
            ],
        ),
    ]
